sudo: required
dist: trusty
install:
  - sudo apt-get install libpam0g-dev libssl-dev
language: cpp
notifications:
  email:
    on_success: change
    on_failure: change
script: ./configure && make -k test && make && ./dual_control && ( nm -u dual_control | grep -v HMAC > /dev/null )
